import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/auth";
import { SignInButton, SignOutButton } from "@/components/auth";
import { SessionProvider } from "next-auth/react"
import { LayoutDashboard, Home, StickyNote, Layers, Flag, Calendar, LifeBuoy, Settings } from "lucide-react";
import Sidebar, { SidebarItem } from "@/components/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <div className="flex">
            <Sidebar>
              <SidebarItem icon={<Home size={20} />} text="Acasă" alert href={"/acasa"} />
              <SidebarItem icon={<LayoutDashboard size={20} />} text="Clase" href={"/clase"} />
              <SidebarItem icon={<StickyNote size={20} />} text="Cărți" href={"/carti"} />
              <hr className="my-3" />
              <SidebarItem icon={<Settings size={20} />} text="Setări" href={"/setari"} />
              <SidebarItem icon={<LifeBuoy size={20} />} text="Help" />
            </Sidebar>
            <div className="flex-1 p-4 bg-gray-50">
              {children}
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
