import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/auth";
import { SignInButton, SignOutButton } from "@/components/auth";
import { SessionProvider } from "next-auth/react"
import { NotebookText, Home, Book, LifeBuoy, Settings, Pen } from "lucide-react";
import Sidebar, { SidebarItem } from "@/components/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <div className="flex">
            <Sidebar>
              <SidebarItem icon={<Home size={20} />} text="Acasă" href={"/"} />
              <SidebarItem icon={<NotebookText size={20} />} text="Clase" href={"/clase"} />
              <SidebarItem icon={<Book size={20} />} text="Manuale" href={"/carti"} />
              <SidebarItem icon={<Pen size={20} />} text="Exersează" href={"/exerseaza"} />
              <hr className="my-3" />
              <SidebarItem icon={<Settings size={20} />} text="Setări" href={"/setari"} />
            </Sidebar>
            <div className="flex-1 p-4 bg-gray-50">
              {children}
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
